### PR TITLE
Merged cells appear as many times as the number of cells they span

### PR DESCRIPTION
**Pull request by Nafees10**
This might not be the best approach towards merged cells, perhaps a flag could be added to switch this behavior.

What this does is repeat the merged cells as many times (vertically and horizontally both) in the output.

### CODE REVIEW

**Comment by TransientResponse** [comment]
I will take a look at this on the weekend, when I have time to give it a proper look. We probably will want to put it behind an option, defaulting to off to avoid breaking anyone's workflow.

Jan 31, 2023 6:07:44 AM Nafees Hassan ***@***.***>:

> This might not be the best approach towards merged cells, perhaps a flag could be added to switch this behavior.
> 
> What this does is repeat the merged cells as many times (vertically and horizontally both) in the output.
> 
> ----------------------------------------
> 
> *You can view, comment on, or merge this pull request online at:*
> 
>   https://github.com/TransientResponse/dlang-ods/pull/1[https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTransientResponse%2Fdlang-ods%2Fpull%2F1&data=05%7C01%7C%7C35125e8a935340919fe708db037b5fca%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638107600638350960%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=erJhyfG4jlyADX4H%2FVKGnZqiEtVDu1EGukX9RvJBV2Y%3D&reserved=0]
> 
> 
> *Commit Summary*
> 
* > 4e1d4b3[https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTransientResponse%2Fdlang-ods%2Fpull%2F1%2Fcommits%2F4e1d4b36fec088b2b1500ac55aa9092ce37ed33a&data=05%7C01%7C%7C35125e8a935340919fe708db037b5fca%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638107600638350960%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vvTT%2B91JWfSuyirIJsYYLtphFG0XKXIQegr0ZfeIe2A%3D&reserved=0] merged cells now appear as many times as the cells they span
* > f99d8a5[https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTransientResponse%2Fdlang-ods%2Fpull%2F1%2Fcommits%2Ff99d8a5987babf3726b8b648623fd9f08e10b9d8&data=05%7C01%7C%7C35125e8a935340919fe708db037b5fca%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638107600638350960%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=EdtUPEN6Y8Lq2HIeyfFjBZuhq7zt2sNmapy2rQzOgrU%3D&reserved=0] Bug fix: sometimes repeated content would not be repated
> 
> *File Changes*
> 
> (1 file[https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTransientResponse%2Fdlang-ods%2Fpull%2F1%2Ffiles&data=05%7C01%7C%7C35125e8a935340919fe708db037b5fca%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638107600638350960%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4ZQp1k4ucG7DY7NxB%2BVBn2s%2BwhBowh%2Fp9nGsQLeJv9w%3D&reserved=0])
> 
* > *M* source/ods.d[https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTransientResponse%2Fdlang-ods%2Fpull%2F1%2Ffiles%23diff-a11e5a65b22de800bcb78e20888bd8023c4deb3fb36a668d4387a651cccaca5e&data=05%7C01%7C%7C35125e8a935340919fe708db037b5fca%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638107600638350960%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=M3W4%2BcdITnKw9pSJS3qtXGhhLmcv4O0CEwqtFwI%2Ffjo%3D&reserved=0] (133)
> 
> *Patch Links:*
> 
* > https://github.com/TransientResponse/dlang-ods/pull/1.patch[https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTransientResponse%2Fdlang-ods%2Fpull%2F1.patch&data=05%7C01%7C%7C35125e8a935340919fe708db037b5fca%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638107600638350960%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FCzV3z%2B77vy%2B8MoSk8DMkpmb5yGjMXWC%2Bzh6gYObVD8%3D&reserved=0]
* > https://github.com/TransientResponse/dlang-ods/pull/1.diff[https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTransientResponse%2Fdlang-ods%2Fpull%2F1.diff&data=05%7C01%7C%7C35125e8a935340919fe708db037b5fca%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638107600638350960%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Y%2B9xdfewJflbJw1wHL10lf006KWgDUiefILBak%2FXe9s%3D&reserved=0]

**Comment by TransientResponse** [comment]
I've added a bool flag in the main class to control whether merged cells are repeated or not. These changes pass my two ODS test sheets, so if you're happy with my additions I'll merge this request.

**Comment by Nafees10** [comment]
It appears to be working as expected for my use case, utilizing merged cells, as well.

**Comment by TransientResponse** [comment]
OK, I'll merge it and tag v0.0.2 then. Thanks for the feature addition.

**Pull request merged**
